[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.13"
remappings = [
    "@endaoment/=lib/endaoment-contracts-v2/src",
    "@uniswap/v3-periphery/=lib/v3-periphery/contracts/",
    "solady/=lib/solady/src/",
]